//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UV7_Program_Manager {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialog() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UV7_Program_Manager.Dialog", typeof(Dialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while loading the background image file
        ///
        ///Detailed error information:
        /// ähnelt.
        /// </summary>
        public static string Config_ImageLoadError {
            get {
                return ResourceManager.GetString("Config.ImageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UV7 Program Manager: Image Load Error ähnelt.
        /// </summary>
        public static string Config_ImageLoadErrorTitle {
            get {
                return ResourceManager.GetString("Config.ImageLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified changes require an immediate application restart.
        ///Do you want to apply these changes?
        ///
        ///Yes: Apply changes and restart
        ///No: Revert changes ähnelt.
        /// </summary>
        public static string Config_ImmediateRestartRequired {
            get {
                return ResourceManager.GetString("Config.ImmediateRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart Required ähnelt.
        /// </summary>
        public static string Config_ImmediateRestartRequiredTitle {
            get {
                return ResourceManager.GetString("Config.ImmediateRestartRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} config file entries could not be loaded
        ///Replace entries with default?
        ///
        ///Yes: Replace missing entries with defaults
        ///No: Load defaults
        ///Cancel: Close application
        ///
        ///Errors:
        ///{1} ähnelt.
        /// </summary>
        public static string Config_LoadError {
            get {
                return ResourceManager.GetString("Config.LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UV7 Program Manager: Config Load Error ähnelt.
        /// </summary>
        public static string Config_LoadErrorTitle {
            get {
                return ResourceManager.GetString("Config.LoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The entry {0} of the config file could not be saved.
        ///Try again?
        ///
        ///Detailed error information:
        ///{1} ähnelt.
        /// </summary>
        public static string Config_SaveError {
            get {
                return ResourceManager.GetString("Config.SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UV7 Program Manager: Config Save Error ähnelt.
        /// </summary>
        public static string Config_SaveErrorTitle {
            get {
                return ResourceManager.GetString("Config.SaveErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UV7 Program Manager - Loading... ähnelt.
        /// </summary>
        public static string Main_Load {
            get {
                return ResourceManager.GetString("Main.Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A major error occured while reading the program groups.
        ///Retry?
        ///
        ///Detailed Error Information:
        /// ähnelt.
        /// </summary>
        public static string Main_MajorLoadError {
            get {
                return ResourceManager.GetString("Main.MajorLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program Group Load Error ähnelt.
        /// </summary>
        public static string Main_MajorLoadErrorTitle {
            get {
                return ResourceManager.GetString("Main.MajorLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Program could not be loaded ähnelt.
        /// </summary>
        public static string Main_StatusStrip_Error {
            get {
                return ResourceManager.GetString("Main.StatusStrip.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Programs could not be loaded ähnelt.
        /// </summary>
        public static string Main_StatusStrip_Errors {
            get {
                return ResourceManager.GetString("Main.StatusStrip.Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Groups ähnelt.
        /// </summary>
        public static string Main_StatusStrip_Groups {
            get {
                return ResourceManager.GetString("Main.StatusStrip.Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading Program Groups... ähnelt.
        /// </summary>
        public static string Main_StatusStrip_Load {
            get {
                return ResourceManager.GetString("Main.StatusStrip.Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program Groups loaded ähnelt.
        /// </summary>
        public static string Main_StatusStrip_LoadFinished {
            get {
                return ResourceManager.GetString("Main.StatusStrip.LoadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program Groups loaded with {0} major errors ähnelt.
        /// </summary>
        public static string Main_StatusStrip_MajorErrors {
            get {
                return ResourceManager.GetString("Main.StatusStrip.MajorErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Programs ähnelt.
        /// </summary>
        public static string Main_StatusStrip_Programs {
            get {
                return ResourceManager.GetString("Main.StatusStrip.Programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while copying new background image ähnelt.
        /// </summary>
        public static string Preferences_CopyErrorTitle {
            get {
                return ResourceManager.GetString("Preferences.CopyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure that you want to reset config to defaults? ähnelt.
        /// </summary>
        public static string Preferences_ResetConfirm {
            get {
                return ResourceManager.GetString("Preferences.ResetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Config Reset Confirmation ähnelt.
        /// </summary>
        public static string Preferences_ResetConfirmTitle {
            get {
                return ResourceManager.GetString("Preferences.ResetConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}
        ///
        ///Additional Error Information:
        ///{1} ähnelt.
        /// </summary>
        public static string Prog_ShortcutDeleteError {
            get {
                return ResourceManager.GetString("Prog.ShortcutDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while deleting shortcut file ähnelt.
        /// </summary>
        public static string Prog_ShortcutDeleteErrorTitle {
            get {
                return ResourceManager.GetString("Prog.ShortcutDeleteErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The item &quot;{0}&quot; that this shortcut refers to has been changed or moved, so this shortcut will no longer work properly.
        ///
        ///Do you want to delete this shortcut? ähnelt.
        /// </summary>
        public static string Prog_ShortcutFileNotFound {
            get {
                return ResourceManager.GetString("Prog.ShortcutFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shortcut Problem ähnelt.
        /// </summary>
        public static string Prog_ShortcutFileNotFoundTitle {
            get {
                return ResourceManager.GetString("Prog.ShortcutFileNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string TaskbarIcon_Cancel {
            get {
                return ResourceManager.GetString("TaskbarIcon.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UV7 Program Manager - Quick Launch ähnelt.
        /// </summary>
        public static string TaskbarIcon_QuickLaunch {
            get {
                return ResourceManager.GetString("TaskbarIcon.QuickLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shut Down Windows... ähnelt.
        /// </summary>
        public static string TaskbarIcon_ShutDown {
            get {
                return ResourceManager.GetString("TaskbarIcon.ShutDown", resourceCulture);
            }
        }
    }
}
